Run cd android   # 如果项目根目录下有 android/ 子目录，改为这个；否则删除这一行
/home/runner/work/_temp/4bd3f256-0053-4f75-8ebd-582d0b7b1e6f.sh: line 1: cd: android: No such file or directory
Error: Process completed with exit code 1.
